//! The detail side of the Navigate section: one item's editor, and the pane that hosts it.
//!
//! The split with `navigate.rs` follows the data: everything here edits ONE item the user has
//! already chosen, while navigate.rs owns choosing it — the list, the selection, the routes,
//! and the commands. The seam between the two files is exactly one field of the window's
//! [`Scene`] (`scene.selected`), which is also the seam between the two layouts: the desktop
//! mounts [`editor_pane`] beside the list, the phone pushes [`editor`] over it, and neither
//! side knows which happened.

use crate::model::{ItemFields, KINDS, Scene};
use crate::res;
use day::prelude::*;

/// The detail pane on a desktop: the selected row's editor, or the empty state.
///
/// `each` over a nought-or-one list rather than a conditional, because the editor has to be
/// rebuilt when the SELECTION changes, not merely shown and hidden — keying it on the id is what
/// gives each item its own scope and its own field bindings.
pub(crate) fn editor_pane(scene: Scene) -> impl Piece {
    column((
        when(
            move || {
                scene
                    .selected
                    .get()
                    .is_none_or(|id| scene.find(id).is_none())
            },
            || {
                // The empty state: centered in the pane, in the platform's secondary label
                // color. Spacers above and below because a column stacks from the top.
                column((
                    spacer(),
                    label(res::str::item_none())
                        .font(Font::Title3)
                        .secondary()
                        // The label fills the width, so the TEXT is what needs centering.
                        .align(TextAlign::Center),
                    spacer(),
                ))
                .align(HAlign::Center)
                // Grown on both sides of the padding: inside so the column fills the pane
                // (vertical centering), outside so the parent sizes it (horizontal).
                .grow()
                .padding(24.0)
                .grow()
            },
        ),
        each(
            items(
                move || {
                    scene
                        .selected
                        .get()
                        .filter(|id| scene.find(*id).is_some())
                        .into_iter()
                        .collect::<Vec<u32>>()
                },
                |id: &u32| *id,
            ),
            move |slot: ItemSlot<u32, u32>| editor(scene, slot.key()),
        ),
    ))
    .grow()
}

/// The editor: every standard two-way binding over one item, in a native form
/// (https://daybrite.dev/docs/forms). Each control binds a FIELD of the item directly —
/// `it.name()` is the read AND the write, generated by `#[derive(Observable)]` on `Item` — so
/// there is no draft state to reconcile, no Save button to forget, and no per-field plumbing:
/// the name is written once, here, instead of once as a signal, once as a write-back, and once
/// in the control (https://daybrite.dev/docs/model).
pub(crate) fn editor(scene: Scene, id: u32) -> impl Piece {
    let it = scene.items.elem(id as u64);

    form((
        section((
            labeled(
                res::str::field_name(),
                text_field(it.name())
                    .placeholder(res::str::field_name_hint())
                    .id("field-name"),
            ),
            labeled(res::str::field_count(), stepper(it.count())),
            // The store keeps the ISO string; the picker speaks `DayDate`. `.map` converts on
            // both sides with plain fns, and the result is still a two-way binding.
            labeled(
                res::str::field_date(),
                day_piece_datetime::date_picker(it.date().map(date_of, iso_of)).id("field-date"),
            ),
        ))
        .title(res::str::section_basics()),
        section((
            labeled(
                res::str::field_kind(),
                picker(KINDS.iter().map(|k| tr(k).format()), it.kind())
                    .segmented()
                    .id("field-kind"),
            ),
            labeled(res::str::field_done(), toggle(it.done()).id("field-done")),
            labeled(
                res::str::field_rating(),
                day_piece_rating::rating(it.rating())
                    .max(5)
                    .id("field-rating"),
            ),
            labeled(
                res::str::field_color(),
                day_piece_colorpicker::color_picker(it.color().map(color_of, hex_of))
                    .id("field-color"),
            ),
        ))
        .title(res::str::section_details()),
        section((text_area(it.notes()).min_lines(5).id("field-notes"),))
            .title(res::str::section_notes()),
    ))
    // A form fills its pane, and on a phone that pane IS the window — so without this the rows
    // run into both edges. The desktop's detail pane inherits the same breathing room.
    .padding(Insets {
        top: 0.0,
        leading: 16.0,
        bottom: 0.0,
        trailing: 16.0,
    })
}

/// A number field with its own increment/decrement pair. No toolkit in Day's set ships a stepper
/// as a single widget, so this is what one looks like composed — three pieces over one binding,
/// which is also the shortest example of how any control you are missing gets built.
fn stepper(value: impl Binding<i64> + Copy) -> impl Piece {
    row((
        button("−")
            .action(move || value.write((value.peek() - 1).max(0)))
            .id("field-count-dec"),
        label(move || value.read().to_string())
            .tabular()
            .reserving("000")
            .id("field-count"),
        button("+")
            .action(move || value.write((value.peek() + 1).min(999)))
            .id("field-count-inc"),
    ))
    .spacing(8.0)
}

// --- the field conversions `.map` binds through: plain fns, so the binding stays `Copy` --------

/// Stored ISO string → the date piece's own type. Malformed values fall back to today: the field
/// is user data.
//
// `&String`, not `&str`, and clippy's ptr_arg is wrong about it here: this is handed to
// `Mapped::map(to: fn(&V) -> U, from: fn(&U) -> V)` as a FUNCTION POINTER, so its type has to be
// exactly `fn(&String) -> _` to match the field's `V = String`. Deref coercion applies to calls,
// not to fn-pointer types, so taking `&str` does not compile at the call site below.
#[allow(clippy::ptr_arg)]
fn date_of(s: &String) -> day_piece_datetime::DayDate {
    day_piece_datetime::DayDate::parse_iso(s).unwrap_or_else(|| {
        // `debug!`, not `warn!` (docs/logging.md): a half-typed date is normal while the user is
        // still typing, so this is a trace for whoever is debugging the field — off by default in
        // a release build, and on with `DAY_LOG=debug`. Levels are how you say that.
        debug!("date {s:?} is not ISO-8601 — showing today");
        day_piece_datetime::DayDate::today()
    })
}

fn iso_of(d: &day_piece_datetime::DayDate) -> String {
    format!("{:04}-{:02}-{:02}", d.year, d.month, d.day)
}

/// `#RRGGBB` → color. Malformed values fall back rather than failing, same reason. Also used by
/// the list rows' kind glyph, which tints with the same color this editor's well sets.
// `&String` for the same reason as `date_of` above: a `Mapped::map` fn pointer over `V = String`.
#[allow(clippy::ptr_arg)]
pub(crate) fn color_of(s: &String) -> Color {
    let h = s.trim_start_matches('#');
    u32::from_str_radix(h, 16)
        .ok()
        .filter(|_| h.len() == 6)
        .map(Color::hex)
        .unwrap_or(Color::hex(0x3B82F6))
}

fn hex_of(c: &Color) -> String {
    let (r, g, b) = (
        (c.r * 255.0).round() as u8,
        (c.g * 255.0).round() as u8,
        (c.b * 255.0).round() as u8,
    );
    format!("#{r:02X}{g:02X}{b:02X}")
}
